version: '3.8'

services:
  queue:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  provider:
    build: ./provider
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - queue
    environment:
      - QUEUE_HOST=queue
